CREATE TABLE [Equipment].[EquipmentList] (
    [EquipmentID]                      INT           IDENTITY (1, 1) NOT NULL,
    [Summary]                          VARCHAR (255) NULL,
    [AllowProRata]                     BIT           DEFAULT ((0)) NOT NULL,
    [LongDescription]                  VARCHAR (MAX) NULL,
    [EquipmentIDInternal]              VARCHAR (30)  NULL,
    [Ownership]                        INT           NULL,
    [LeaseHolder]                      VARCHAR (50)  NULL,
    [Mobility]                         INT           NULL,
    [SerialNumber]                     VARCHAR (30)  NULL,
    [ParentEquipmentID]                INT           NULL,
    [FinalDisposition]                 INT           NULL,
    [FinalDispositionDate]             DATETIME      NULL,
    [FinalDispositionSoldTo]           VARCHAR (100) NULL,
    [FinalDispositionAddress]          VARCHAR (255) NULL,
    [FinalDispositionPhone]            VARCHAR (25)  NULL,
    [FinalDispositionDLNumber]         VARCHAR (25)  NULL,
    [FinalDispositionReportedTo]       VARCHAR (100) NULL,
    [FinalDispositionReportNumber]     VARCHAR (25)  NULL,
    [FinalDispositionSummary]          VARCHAR (150) NULL,
    [FinalDispositionCircumstances]    VARCHAR (MAX) NULL,
    [FinalDispositionLostBy]           VARCHAR (100) NULL,
    [FinalDispositionDonatedTo]        VARCHAR (100) NULL,
    [FinalDispositionQualifiedCharity] BIT           DEFAULT ((0)) NOT NULL,
    [AddID]                            INT           NULL,
    [AddDate]                          DATETIME      DEFAULT (getdate()) NULL,
    [ChangeID]                         INT           NULL,
    [ChangeDate]                       DATETIME      NULL,
    [QRPrinted]                        INT           DEFAULT ((0)) NULL,
    [NextRegularServiceDue]            DATETIME      NULL,
    [ServiceType]                      VARCHAR (100) NULL,
    [RemindersToID]                    INT           NULL,
    [DateServiceCompleted]             DATETIME      NULL,
    [ShowAppLongDescription]           BIT           DEFAULT ((1)) NOT NULL,
    [ShowAppEquipmentIDInternal]       BIT           DEFAULT ((1)) NOT NULL,
    [ShowAppOwnership]                 BIT           DEFAULT ((1)) NOT NULL,
    [ShowAppMobility]                  BIT           DEFAULT ((1)) NOT NULL,
    [ShowAppSerialNumber]              BIT           DEFAULT ((1)) NOT NULL,
    [ShowAppNextRegularServiceDue]     BIT           DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_EquipmentList] PRIMARY KEY CLUSTERED ([EquipmentID] ASC)
);


GO

