CREATE TABLE [dbo].[tblProjectWork] (
    [UserFld1]              NVARCHAR (10)   NULL,
    [ProjectWorkID]         INT             IDENTITY (1, 1) NOT NULL,
    [WorkStatus]            NVARCHAR (1)    NULL,
    [DBStatus]              NVARCHAR (50)   NULL,
    [WorkItem]              NVARCHAR (50)   NULL,
    [Vendor]                INT             NULL,
    [WorkDays]              DECIMAL (16, 2) NULL,
    [AvailWorkDays]         INT             NULL,
    [EventNum1]             INT             NULL,
    [EventNum2]             INT             NULL,
    [EventNum3]             INT             NULL,
    [StartDate]             DATETIME        NULL,
    [EndDate]               DATETIME        NULL,
    [HardEndDate]           DATETIME        NULL,
    [InteriorAccess]        NVARCHAR (3)    NULL,
    [AffectedProject]       NVARCHAR (3)    NULL,
    [CIMASupHrs]            INT             NULL,
    [CIMALabor1]            NVARCHAR (15)   NULL,
    [CIMALabor1Hrs]         INT             NULL,
    [CIMALabor2]            NVARCHAR (15)   NULL,
    [CIMALabor2Hrs]         INT             NULL,
    [CIMASalesHrs]          INT             NULL,
    [ConstructionDivCode]   NVARCHAR (15)   NULL,
    [TypicalLeadTimeDays]   INT             NULL,
    [ProjectID]             INT             NULL,
    [CalcDone]              NVARCHAR (1)    NULL,
    [DateStatus]            VARCHAR (200)   NULL,
    [PWA]                   BIT             DEFAULT ((0)) NOT NULL,
    [StartDateLastModified] DATETIME        NULL,
    [EndDateLastModified]   DATETIME        NULL,
    [FluffWorkDays]         INT             NULL,
    [LagWorkDays]           INT             NULL,
    [ShowCustomer]          BIT             DEFAULT ((1)) NOT NULL,
    [Scope]                 VARCHAR (MAX)   NULL,
    [Comments]              VARCHAR (MAX)   NULL,
    [HasScopeComments]      BIT             DEFAULT ((0)) NOT NULL,
    [PWAID]                 INT             NULL,
    [PWAAdd]                BIT             DEFAULT ((0)) NOT NULL,
    [PWADetailStatusID]     INT             NULL,
    CONSTRAINT [ProjectWorkID] PRIMARY KEY CLUSTERED ([ProjectWorkID] ASC)
);


GO

