CREATE TABLE [dbo].[tblSubPayApp_OLD] (
    [SubPayAppId]               INT             IDENTITY (1, 1) NOT NULL,
    [AppType]                   NCHAR (10)      CONSTRAINT [DF_tblSubPayApp_AppType] DEFAULT (N'Partial') NULL,
    [AppStatus]                 VARCHAR (15)    CONSTRAINT [DF_tblSubPayApp_AppStatus] DEFAULT ('Incomplete') NULL,
    [PWALogID]                  INT             NULL,
    [SubPayAppSequence]         INT             NULL,
    [OwnerPayAppNumber]         INT             NULL,
    [DateIssued]                DATETIME        NULL,
    [DateLastModified]          DATETIME        NULL,
    [DateDue]                   DATETIME        NULL,
    [DateReceived]              DATETIME        NULL,
    [LienRelease]               NCHAR (20)      NULL,
    [VendorInvoiceNo]           NCHAR (20)      NULL,
    [HoldRetainage]             BIT             DEFAULT ((1)) NULL,
    [HoldPercent]               DECIMAL (18, 2) DEFAULT ((0.1)) NULL,
    [InvoicePath]               NVARCHAR (MAX)  NULL,
    [PayAppPath]                NVARCHAR (MAX)  NULL,
    [ConditionalWaiverPath]     NVARCHAR (MAX)  NULL,
    [UnconditionalWaiverPath]   NVARCHAR (MAX)  NULL,
    [PctComplete]               DECIMAL (18, 2) NULL,
    [WorkCompleted]             MONEY           NULL,
    [StoredMaterial]            MONEY           NULL,
    [Retainage]                 MONEY           NULL,
    [SubPayAmount]              MONEY           NULL,
    [PaymentTypeID]             INT             NULL,
    [CheckNumber]               VARCHAR (50)    NULL,
    [BankIDNumber]              VARCHAR (50)    NULL,
    [WorkThrough]               DATETIME        NULL,
    [PaymentApprovedOn]         DATETIME        NULL,
    [IsDeleted]                 VARCHAR (1)     DEFAULT ('N') NOT NULL,
    [SubPayAppSequenceRevision] INT             DEFAULT ((0)) NOT NULL,
    [StopPayUser]               VARCHAR (255)   NULL,
    [StopPayOn]                 DATETIME        NULL,
    [BillID]                    INT             NULL,
    [AddDate]                   DATETIME        CONSTRAINT [DF_tblSubPayApp_AddDate] DEFAULT (getdate()) NULL,
    [ChangeDate]                DATETIME        NULL,
    [AddID]                     INT             NULL,
    [ChangeID]                  INT             NULL,
    [appStartDate]              DATETIME        NULL,
    [appEndDate]                DATETIME        NULL,
    [Approver1]                 INT             NULL,
    [Approver2]                 INT             NULL,
    [Approver1DateTime]         DATETIME        NULL,
    [Approver2DateTime]         DATETIME        NULL,
    [onHold]                    INT             NULL,
    [onHoldTill]                DATETIME        NULL,
    [approveStatus]             INT             NULL,
    [approvalComments]          VARCHAR (MAX)   NULL,
    [CheckStatus]               VARCHAR (50)    NULL,
    [RetainagePayOut]           MONEY           NULL,
    [HaveStoredMaterial]        INT             NULL,
    [SubPayAppDate]             DATETIME        NULL,
    CONSTRAINT [PK_tblSubPayApp] PRIMARY KEY CLUSTERED ([SubPayAppId] ASC)
);


GO

